version: '3.3'
services:
  search-enabler:
    image: gitlab.iotcrawler.net:4567/search-enabler/search-enabler/master:289037f63d6800660d39fb8c5fe7624fadcfd583
    environment:
      - IOTCRAWLER_ORCHESTRATOR_URL=http://155.54.95.248:9090/ngsi-ld/
    ports:
      - "8080:8080"
