apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: search-enabler-ingress
spec:
  rules:
    - host: {{.Values.service.url}}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "search-enabler"
              servicePort: 8080
