apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.gitlab.app }}-ingress
spec:
  rules:
    - host: {{.Release.Name}}.35.241.228.250.nip.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ .Values.gitlab.app }}
              servicePort: 8080
