apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: search-enabler-ingress
spec:
  rules:
    {{ if eq .Values.gitlab.env "staging" }}
    - host: staging.search-enabler.iotcrawler.eu
      {{ else }}
    - host: search-enabler.iotcrawler.eu
    {{ end }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "search-enabler"
              servicePort: 8080
    #- host: {{ .Values.gitlab.env }}.35.241.228.250.nip.io