apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: search-enabler
  name: search-enabler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search-enabler
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: search-enabler
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        #image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        image: "{{ .Values.image.repository }}:0606de1276e1019ee81b9f5bcd257c9602bf0d9d"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: "port80"
            containerPort: 8080

        env:
          - name: VERSION
            value: "{{ .Values.image.tag }}"
