apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: search_enabler
  name: orchestrator
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: search_enabler
status:
  loadBalancer: {}
