apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: search-enabler
  name: {{ .Values.gitlab.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search-enabler
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: search-enabler
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        #image: "{{ .Values.image.repository }}:d4481db3977214554945858c1f0e073ad16c8466"
        #image: "{{ .Values.image.url }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: "port8080"
            containerPort: 8080
        env:
          - name: VERSION
            value: "{{ .Values.image.tag }}"
          - name: IOTCRAWLER_ORCHESTRATOR_URL
            value: "http://scorpio.scorpiobroker-46-production:9090/ngsi-ld/"
            #value: "http://155.54.95.248:9090/ngsi-ld/"
