apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.gitlab.env }}
  name: {{ .Values.gitlab.env }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    io.kompose.service: {{ .Values.gitlab.env }}
status:
  loadBalancer: {}
